const problems = [
  {id:'001',title:'Customers Who Never Order',level:'Easy',tag:'JOIN',desc:`<p>Write a query to find all customers who have never placed an order.</p><p>Return the result table in <b>any order</b>.</p>`,example:`Input:\nCustomers\n+----+-------+\n| id | name  |\n+----+-------+\n| 1  | Joe   |\n| 2  | Henry |\n+----+-------+\n\nOrders\n+----+------------+\n| id | customerId |\n+----+------------+\n| 1  | 2          |\n+----+------------+\n\nOutput:\n+----------+\n| Customers|\n+----------+\n| Joe      |\n+----------+\n\nSchema:\nCustomers(id INTEGER, name TEXT)\nOrders(id INTEGER, customerId INTEGER)`,query:'SELECT name AS Customers\nFROM Customers\nWHERE id NOT IN (SELECT customerId FROM Orders);',cols:['Customers'],rows:[['Joe']],setup:`CREATE TABLE Customers (id INTEGER, name TEXT); INSERT INTO Customers VALUES (1, 'Joe'), (2, 'Henry'), (3, 'Max'); CREATE TABLE Orders (id INTEGER, customerId INTEGER); INSERT INTO Orders VALUES (1, 2);`,schema:[['Customers','id INTEGER · name TEXT'],['Orders','id INTEGER · customerId INTEGER']],hint:'A LEFT JOIN lets you keep every customer, including those without a matching order.'},
  {id:'002',title:'Second Highest Salary',level:'Medium',tag:'AGGREGATION',desc:`<p>Write a query to find the second highest <b>distinct</b> salary from the <code>Employee</code> table. If there is no second highest salary, return <code>null</code>.</p>`,example:`Input:\nEmployee\n+----+--------+\n| id | salary |\n+----+--------+\n| 1  | 100    |\n| 2  | 200    |\n| 3  | 300    |\n+----+--------+\n\nOutput:\n+---------------------+\n| SecondHighestSalary |\n+---------------------+\n| 200                 |\n+---------------------+\n\nSchema:\nEmployee(id INTEGER, salary INTEGER)`,query:'SELECT MAX(salary) AS SecondHighestSalary\nFROM Employee\nWHERE salary < (SELECT MAX(salary) FROM Employee);',cols:['SecondHighestSalary'],rows:[['200']],setup:`CREATE TABLE Employee (id INTEGER, salary INTEGER); INSERT INTO Employee VALUES (1, 100), (2, 200), (3, 300), (4, 300);`,schema:[['Employee','id INTEGER · salary INTEGER']],hint:'Think about how you can order values and limit the result to one row.'},
  {id:'003',title:'Rising Temperature',level:'Easy',tag:'DATE',desc:`<p>Find all dates where the temperature was higher than the previous day.</p><p>Return the <code>id</code> of each matching record.</p>`,example:`Input:\nWeather\n+----+------------+-------------+\n| id | recordDate | temperature |\n+----+------------+-------------+\n| 1  | 2015-01-01 | 10          |\n| 2  | 2015-01-02 | 25          |\n+----+------------+-------------+\n\nOutput:\n+----+\n| id |\n+----+\n| 2  |\n+----+\n\nSchema:\nWeather(id INTEGER, record_date DATE, temperature INTEGER)`,query:"SELECT w1.id\nFROM weather w1\nJOIN weather w2\n  ON w1.record_date = w2.record_date + INTERVAL '1 day'\nWHERE w1.temperature > w2.temperature;",cols:['id'],rows:[['2']],setup:`CREATE TABLE weather (id INTEGER, record_date DATE, temperature INTEGER); INSERT INTO weather VALUES (1, '2015-01-01', 10), (2, '2015-01-02', 25), (3, '2015-01-03', 20);`,schema:[['weather','id INTEGER · record_date DATE · temperature INTEGER']],hint:'PostgreSQL can add an interval directly to a DATE. Compare each row to a second copy shifted by one day.'},
  {id:'004',title:'Department Top Three Salaries',level:'Hard',tag:'WINDOW',desc:`<p>Find employees who earn one of the top three unique salaries in each department.</p>`,example:`Input:\nEmployee and Department tables\n\nOutput:\nEmployee names, department names, and salaries\n\nSchema:\nEmployee(id, name, salary, departmentId)\nDepartment(id, name)`,query:'SELECT d.name AS Department, e.name AS Employee, e.salary AS Salary\nFROM Employee e\nJOIN Department d ON e.departmentId = d.id\nWHERE 3 > (\n  SELECT COUNT(DISTINCT e2.salary)\n  FROM Employee e2\n  WHERE e2.departmentId = e.departmentId\n    AND e2.salary > e.salary\n);',cols:['Department','Employee','Salary'],rows:[['IT','Max','90000'],['Sales','John','85000']],setup:`CREATE TABLE Department (id INTEGER, name TEXT); INSERT INTO Department VALUES (1, 'IT'), (2, 'Sales'); CREATE TABLE Employee (id INTEGER, name TEXT, salary INTEGER, departmentId INTEGER); INSERT INTO Employee VALUES (1, 'Max', 90000, 1), (2, 'Joe', 85000, 1), (3, 'John', 85000, 2), (4, 'Randy', 70000, 2);`,schema:[['Employee','id INTEGER · name TEXT · salary INTEGER · departmentId INTEGER'],['Department','id INTEGER · name TEXT']],hint:'Ranking functions are ideal here: partition rows by department, then rank salaries.'},
  {id:'005',title:'Duplicate Emails',level:'Easy',tag:'GROUP BY',desc:`<p>Write a query to report all duplicate emails in the <code>Person</code> table.</p>`,example:`Input:\nPerson\n+----+---------+\n| id | email   |\n+----+---------+\n| 1  | a@x.com |\n| 2  | a@x.com |\n+----+---------+\n\nOutput:\n+---------+\n| Email   |\n+---------+\n| a@x.com |\n+---------+\n\nSchema:\nPerson(id INTEGER, email TEXT)`,query:'SELECT email AS Email\nFROM Person\nGROUP BY email\nHAVING COUNT(*) > 1;',cols:['Email'],rows:[['a@x.com']],setup:`CREATE TABLE Person (id INTEGER, email TEXT); INSERT INTO Person VALUES (1, 'a@x.com'), (2, 'a@x.com'), (3, 'b@x.com');`,schema:[['Person','id INTEGER · email TEXT']],hint:'Group the rows by email, then keep only groups with more than one row.'}
];
let current = 1; let activeTab = 'results'; let PGlite;
const $ = s => document.querySelector(s);
function renderList(){ $('#problemList').innerHTML=problems.map((p,i)=>`<button class="problem-item ${i===current?'active':''}" data-i="${i}"><span class="problem-id">${p.id}</span><span class="problem-name">${p.title}</span><span class="level-dot ${p.level.toLowerCase()}"></span></button>`).join(''); document.querySelectorAll('.problem-item').forEach(b=>b.onclick=()=>loadProblem(+b.dataset.i)); }
function loadProblem(i){current=i; const p=problems[i]; $('#crumbTitle').textContent=p.title; $('#problemNumber').textContent='PROBLEM '+p.id; $('#problemTitle').textContent=p.title; $('#difficulty').textContent=p.level; $('#difficulty').className='difficulty '+p.level.toLowerCase(); $('.tags').innerHTML=`<span>${p.tag}</span>`; $('#description').innerHTML=p.desc; $('#exampleCode').textContent=p.example; $('#hintText').textContent=p.hint; $('#queryEditor').value=p.query; updateLines(); $('#resultsContent').innerHTML='<div class="empty-state"><div class="empty-icon">▤</div><div>Run your query to see results here.</div></div>'; $('#resultBadge').textContent=''; $('#resultStatus').textContent='Ready to run'; activeTab='results'; setTabs(); renderList(); }
function updateLines(){const n=$('#queryEditor').value.split('\n').length; $('#lineNumbers').innerHTML=Array.from({length:n},(_,i)=>i+1).join('<br>');}
function setTabs(){document.querySelectorAll('.result-tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===activeTab)); if(activeTab==='schema'){ const cards=problems[current].schema.map(([table,columns])=>`<div class="schema-card"><h3>${table}</h3><p>${columns}</p></div>`).join(''); $('#resultsContent').innerHTML=`<div class="schema-grid">${cards}</div>`; } }
$('#queryEditor').addEventListener('input',updateLines); $('#queryEditor').addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')runQuery(); if(e.key==='Tab'){e.preventDefault(); const s=e.target.selectionStart;e.target.setRangeText('  ',s,e.target.selectionEnd,'end');updateLines();}});
async function runQuery(){const p=problems[current], q=$('#queryEditor').value.trim(); if(!q){showToast('Write a query first');return;} if(!PGlite){showToast('The PostgreSQL engine is still loading');return;} activeTab='results'; setTabs(); const start=performance.now(); try { const db=new PGlite(); await db.exec(p.setup); const result=await db.query(q); const elapsed=Math.max(1,Math.round(performance.now()-start)); const rows=result.rows || []; const columns=rows.length ? Object.keys(rows[0]) : []; if(!rows.length){ $('#resultsContent').innerHTML='<div class="empty-state"><div class="empty-icon">✓</div><div>Query ran successfully. No rows returned.</div></div>'; $('#resultBadge').textContent='0'; } else { $('#resultBadge').textContent=rows.length; $('#resultsContent').innerHTML=`<table class="data-table"><thead><tr>${columns.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(column=>`<td>${row[column]===null?'NULL':row[column]}</td>`).join('')}</tr>`).join('')}</tbody></table>`;} $('#resultStatus').innerHTML=`<span class="success">●</span> Executed · ${elapsed} ms`; await db.close(); showToast('Query executed successfully'); } catch(error){$('#resultStatus').textContent='Query error'; $('#resultBadge').textContent=''; $('#resultsContent').innerHTML=`<div class="empty-state"><div class="empty-icon">!</div><div><strong>SQL error</strong><br>${error.message}</div></div>`;}}
$('#runButton').onclick=runQuery; $('#resetButton').onclick=()=>{ $('#queryEditor').value=problems[current].query; updateLines(); showToast('Starter query restored');}; $('#hintButton').onclick=()=>$('.hint-box').classList.toggle('open'); document.querySelectorAll('.result-tab').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;setTabs();}); $('#menuButton').onclick=()=>$('#sidebar').classList.toggle('open');
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
async function startSql(){ try { const module=await import('https://cdn.jsdelivr.net/npm/@electric-sql/pglite@0.2.17/+esm'); PGlite=module.PGlite; $('#resultStatus').textContent='PostgreSQL engine ready';} catch(error){$('#resultStatus').textContent='Unable to load PostgreSQL engine';} }
var supabaseClient = window.supabase.createClient(window.QUERYNEST_CONFIG.supabaseUrl, window.QUERYNEST_CONFIG.supabasePublishableKey);
function showAuth(show){ $('#authModal').classList.toggle('open',show); $('#authModal').setAttribute('aria-hidden',String(!show)); }
async function updateSignedInUser(session){ if(!session){ $('#profileName').textContent='Guest'; $('#profileRole').textContent='Sign in to save progress'; $('#avatar').textContent='QN'; showAuth(true); return; } const user=session.user; const displayName=user.user_metadata?.display_name || user.email.split('@')[0]; $('#profileName').textContent=displayName; $('#profileRole').textContent='SQL Explorer'; $('#avatar').textContent=displayName.slice(0,2).toUpperCase(); showAuth(false); const profile=await supabaseClient.from('profiles').select('id').eq('id',user.id).maybeSingle(); if(!profile.data) await supabaseClient.from('profiles').insert({id:user.id,display_name:displayName}); }
$('#authForm').addEventListener('submit',async event=>{event.preventDefault(); const submit=event.target.querySelector('button'); submit.disabled=true; $('#authError').textContent=''; const result=await supabaseClient.auth.signInWithPassword({email:$('#authEmail').value,password:$('#authPassword').value}); submit.disabled=false; if(result.error) $('#authError').textContent=result.error.message;});
$('#signOutButton').onclick=()=>supabaseClient.auth.signOut();
var executePracticeQuery = runQuery;
runQuery = async function(){ await executePracticeQuery(); const { data:{session} }=await supabaseClient.auth.getSession(); if(session) await supabaseClient.rpc('record_attempt',{p_problem_code:problems[current].id,p_query:$('#queryEditor').value.trim()}); };
$('#runButton').onclick=runQuery;
supabaseClient.auth.onAuthStateChange((_event,session)=>updateSignedInUser(session));
renderList();loadProblem(1); startSql();
