const labTemplates = [
  ['01','Easy','Explore the data','SELECT',d=>`Return every column from <code>${d.primary}</code>. Use this to understand the available data before answering analytical questions.`],
  ['02','Easy','Filter a business segment','WHERE',d=>`Find ${d.primary} records that match a useful business condition. Practice filtering before joining related tables.`],
  ['03','Easy','Sort the latest activity','ORDER BY',d=>`Return the most recent ${d.related} records, sorted newest first. Limit the result to a practical review size.`],
  ['04','Easy','Count important records','COUNT',d=>`Count the total number of ${d.primary} records. Return the count with a clear column alias.`],
  ['05','Easy','Find missing relationships','JOIN',d=>`Find ${d.primary} records that have no related ${d.related} record. Return meaningful identifying columns.`],
  ['06','Easy','Summarize by category','GROUP BY',d=>`Group ${d.primary} by a relevant category and return the count for each group.`],
  ['07','Medium','Calculate totals per entity','AGGREGATION',d=>`Join <code>${d.primary}</code> and <code>${d.related}</code>, then calculate the total activity for every ${d.entity}.`],
  ['08','Medium','Find above-average activity','SUBQUERY',d=>`Find ${d.entityPlural} whose related activity is above the overall average. Use a subquery or CTE.`],
  ['09','Medium','Build a recent activity report','DATE',d=>`Create a report for activity in the last 30 days. Use PostgreSQL date arithmetic with <code>INTERVAL</code>.`],
  ['10','Medium','Rank the top performers','WINDOW',d=>`Rank ${d.entityPlural} by their total related activity. Include ties using an appropriate window function.`],
  ['11','Medium','Measure month-over-month change','CTE',d=>`Aggregate the activity by month, then calculate change from the previous month using a CTE and <code>LAG()</code>.`],
  ['12','Medium','Identify repeat behaviour','HAVING',d=>`Find ${d.entityPlural} with more than one related record. Return the entity and number of occurrences.`],
  ['13','Medium','Compare segments','CASE',d=>`Create segments using <code>CASE</code> based on total related activity, then count ${d.entityPlural} in each segment.`],
  ['14','Medium','Find the first event','WINDOW',d=>`For each ${d.entity}, return their first related event using <code>ROW_NUMBER()</code> or <code>MIN()</code>.`],
  ['15','Hard','Top three within each group','WINDOW',d=>`Return the top three ${d.related} values within every logical group. Use <code>DENSE_RANK()</code>.`],
  ['16','Hard','Detect data anomalies','SELF JOIN',d=>`Find unusual patterns by comparing a ${d.entity}'s related values to their previous record or group average.`],
  ['17','Hard','Build a retention cohort','CTE',d=>`Assign ${d.entityPlural} to a cohort based on their first activity month, then measure continuing activity by cohort.`],
  ['18','Hard','Calculate a running total','WINDOW',d=>`Return each related record with a running total per ${d.entity}. Order the window carefully.`],
  ['19','Hard','Find consecutive activity','GAPS & ISLANDS',d=>`Identify ${d.entityPlural} with activity on consecutive dates. Use the gaps-and-islands pattern.`],
  ['20','Hard','Create an executive report','CTE',d=>`Combine multiple CTEs into one concise report: totals, rankings, and the leading ${d.entity} for every category.`]
];

const domains = [
  {key:'banking',name:'Banking',icon:'◈',primary:'accounts',related:'transactions',entity:'customer',entityPlural:'customers',tables:['customers','accounts','transactions'],schema:['customers: id, full_name, city','accounts: id, customer_id, account_type, opened_on','transactions: id, account_id, amount, transaction_at'],setup:`CREATE TABLE customers (id INTEGER PRIMARY KEY, full_name TEXT, city TEXT); CREATE TABLE accounts (id INTEGER PRIMARY KEY, customer_id INTEGER, account_type TEXT, opened_on DATE); CREATE TABLE transactions (id INTEGER PRIMARY KEY, account_id INTEGER, amount NUMERIC, transaction_at DATE); INSERT INTO customers VALUES (1,'Asha Rao','Mumbai'),(2,'Noah Shah','Delhi'),(3,'Maya Lee','Pune'); INSERT INTO accounts VALUES (101,1,'Savings','2024-01-10'),(102,1,'Current','2024-03-02'),(103,2,'Savings','2024-02-20'); INSERT INTO transactions VALUES (1,101,500,'2025-01-02'),(2,101,-75,'2025-01-03'),(3,103,900,'2025-02-02'),(4,103,-110,'2025-02-04');`},
  {key:'healthcare',name:'Healthcare',icon:'✚',primary:'patients',related:'appointments',entity:'patient',entityPlural:'patients',tables:['patients','providers','appointments','claims'],schema:['patients: id, name, birth_date','providers: id, name, specialty','appointments: id, patient_id, provider_id, scheduled_at','claims: id, appointment_id, amount, status'],setup:`CREATE TABLE patients (id INTEGER PRIMARY KEY, name TEXT, birth_date DATE); CREATE TABLE providers (id INTEGER PRIMARY KEY, name TEXT, specialty TEXT); CREATE TABLE appointments (id INTEGER PRIMARY KEY, patient_id INTEGER, provider_id INTEGER, scheduled_at DATE); CREATE TABLE claims (id INTEGER PRIMARY KEY, appointment_id INTEGER, amount NUMERIC, status TEXT); INSERT INTO patients VALUES (1,'Mira Patel','1990-06-12'),(2,'Arjun Bose','1981-04-03'),(3,'Eva Chen','1995-11-18'); INSERT INTO providers VALUES (10,'Dr Singh','Cardiology'),(11,'Dr Miller','General'); INSERT INTO appointments VALUES (100,1,10,'2025-01-10'),(101,1,11,'2025-02-13'),(102,2,10,'2025-02-20'); INSERT INTO claims VALUES (1,100,450,'paid'),(2,101,180,'pending'),(3,102,700,'paid');`},
  {key:'retail',name:'Retail',icon:'▦',primary:'customers',related:'orders',entity:'customer',entityPlural:'customers',tables:['customers','products','orders','order_items'],schema:['customers: id, name, segment','products: id, name, category, price','orders: id, customer_id, ordered_at','order_items: order_id, product_id, quantity'],setup:`CREATE TABLE customers (id INTEGER PRIMARY KEY, name TEXT, segment TEXT); CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT, category TEXT, price NUMERIC); CREATE TABLE orders (id INTEGER PRIMARY KEY, customer_id INTEGER, ordered_at DATE); CREATE TABLE order_items (order_id INTEGER, product_id INTEGER, quantity INTEGER); INSERT INTO customers VALUES (1,'Isha','Gold'),(2,'Ben','Silver'),(3,'Zoe','Gold'); INSERT INTO products VALUES (10,'Headphones','Electronics',80),(11,'Notebook','Stationery',8); INSERT INTO orders VALUES (100,1,'2025-01-04'),(101,1,'2025-02-03'),(102,2,'2025-02-11'); INSERT INTO order_items VALUES (100,10,1),(100,11,2),(101,11,5),(102,10,1);`},
  {key:'workforce',name:'Workforce',icon:'♙',primary:'employees',related:'payroll',entity:'employee',entityPlural:'employees',tables:['departments','employees','payroll','reviews'],schema:['departments: id, name','employees: id, department_id, name, hired_on','payroll: id, employee_id, salary, paid_on','reviews: id, employee_id, score, reviewed_on'],setup:`CREATE TABLE departments (id INTEGER PRIMARY KEY, name TEXT); CREATE TABLE employees (id INTEGER PRIMARY KEY, department_id INTEGER, name TEXT, hired_on DATE); CREATE TABLE payroll (id INTEGER PRIMARY KEY, employee_id INTEGER, salary NUMERIC, paid_on DATE); CREATE TABLE reviews (id INTEGER PRIMARY KEY, employee_id INTEGER, score INTEGER, reviewed_on DATE); INSERT INTO departments VALUES (1,'Engineering'),(2,'Sales'); INSERT INTO employees VALUES (1,1,'Ria','2022-01-12'),(2,1,'Omar','2023-04-20'),(3,2,'Lena','2021-11-03'); INSERT INTO payroll VALUES (1,1,90000,'2025-01-31'),(2,2,78000,'2025-01-31'),(3,3,85000,'2025-01-31'); INSERT INTO reviews VALUES (1,1,5,'2025-02-01'),(2,2,4,'2025-02-01'),(3,3,5,'2025-02-01');`},
  {key:'travel',name:'Travel',icon:'✈',primary:'travelers',related:'bookings',entity:'traveler',entityPlural:'travelers',tables:['travelers','flights','bookings','payments'],schema:['travelers: id, name, country','flights: id, route, departed_at','bookings: id, traveler_id, flight_id, booked_at','payments: id, booking_id, amount, paid_at'],setup:`CREATE TABLE travelers (id INTEGER PRIMARY KEY, name TEXT, country TEXT); CREATE TABLE flights (id INTEGER PRIMARY KEY, route TEXT, departed_at DATE); CREATE TABLE bookings (id INTEGER PRIMARY KEY, traveler_id INTEGER, flight_id INTEGER, booked_at DATE); CREATE TABLE payments (id INTEGER PRIMARY KEY, booking_id INTEGER, amount NUMERIC, paid_at DATE); INSERT INTO travelers VALUES (1,'Nia','India'),(2,'Kai','Singapore'),(3,'Sam','India'); INSERT INTO flights VALUES (1,'DEL-BOM','2025-03-11'),(2,'BOM-SIN','2025-04-04'); INSERT INTO bookings VALUES (1,1,1,'2025-02-12'),(2,1,2,'2025-03-01'),(3,2,2,'2025-03-02'); INSERT INTO payments VALUES (1,1,120,'2025-02-12'),(2,2,380,'2025-03-01'),(3,3,380,'2025-03-02');`},
  {key:'streaming',name:'Streaming',icon:'▶',primary:'users',related:'watch_history',entity:'viewer',entityPlural:'viewers',tables:['users','subscriptions','content','watch_history'],schema:['users: id, name, country','subscriptions: id, user_id, plan, started_at','content: id, title, genre','watch_history: id, user_id, content_id, watched_at, minutes'],setup:`CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, country TEXT); CREATE TABLE subscriptions (id INTEGER PRIMARY KEY, user_id INTEGER, plan TEXT, started_at DATE); CREATE TABLE content (id INTEGER PRIMARY KEY, title TEXT, genre TEXT); CREATE TABLE watch_history (id INTEGER PRIMARY KEY, user_id INTEGER, content_id INTEGER, watched_at DATE, minutes INTEGER); INSERT INTO users VALUES (1,'Ari','India'),(2,'Ivy','UK'),(3,'Dev','India'); INSERT INTO subscriptions VALUES (1,1,'Premium','2025-01-01'),(2,2,'Basic','2025-02-01'); INSERT INTO content VALUES (1,'Orbit','Sci-Fi'),(2,'Harbor','Drama'); INSERT INTO watch_history VALUES (1,1,1,'2025-02-02',80),(2,1,2,'2025-02-03',45),(3,2,1,'2025-02-05',70);`},
  {key:'logistics',name:'Logistics',icon:'▣',primary:'shipments',related:'delivery_events',entity:'shipment',entityPlural:'shipments',tables:['warehouses','shipments','delivery_events','carriers'],schema:['warehouses: id, city, capacity','shipments: id, warehouse_id, carrier_id, shipped_at','delivery_events: id, shipment_id, event_type, occurred_at','carriers: id, name, region'],setup:`CREATE TABLE warehouses (id INTEGER PRIMARY KEY, city TEXT, capacity INTEGER); CREATE TABLE carriers (id INTEGER PRIMARY KEY, name TEXT, region TEXT); CREATE TABLE shipments (id INTEGER PRIMARY KEY, warehouse_id INTEGER, carrier_id INTEGER, shipped_at DATE); CREATE TABLE delivery_events (id INTEGER PRIMARY KEY, shipment_id INTEGER, event_type TEXT, occurred_at DATE); INSERT INTO warehouses VALUES (1,'Mumbai',500),(2,'Delhi',300); INSERT INTO carriers VALUES (1,'Swift','North'),(2,'ParcelPro','West'); INSERT INTO shipments VALUES (1,1,1,'2025-01-01'),(2,1,2,'2025-01-03'),(3,2,1,'2025-02-01'); INSERT INTO delivery_events VALUES (1,1,'picked','2025-01-01'),(2,1,'delivered','2025-01-03'),(3,2,'picked','2025-01-03'),(4,2,'delivered','2025-01-05');`},
  {key:'education',name:'Education',icon:'▤',primary:'students',related:'enrollments',entity:'student',entityPlural:'students',tables:['students','courses','enrollments','assessments'],schema:['students: id, name, cohort','courses: id, title, subject','enrollments: id, student_id, course_id, enrolled_at','assessments: id, enrollment_id, score, submitted_at'],setup:`CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT, cohort TEXT); CREATE TABLE courses (id INTEGER PRIMARY KEY, title TEXT, subject TEXT); CREATE TABLE enrollments (id INTEGER PRIMARY KEY, student_id INTEGER, course_id INTEGER, enrolled_at DATE); CREATE TABLE assessments (id INTEGER PRIMARY KEY, enrollment_id INTEGER, score INTEGER, submitted_at DATE); INSERT INTO students VALUES (1,'Diya','2025'),(2,'Rahul','2025'),(3,'Mei','2026'); INSERT INTO courses VALUES (1,'SQL Foundations','Data'),(2,'Analytics','Data'); INSERT INTO enrollments VALUES (1,1,1,'2025-01-10'),(2,1,2,'2025-02-10'),(3,2,1,'2025-02-12'); INSERT INTO assessments VALUES (1,1,92,'2025-01-20'),(2,2,88,'2025-02-20'),(3,3,75,'2025-02-24');`},
  {key:'hospitality',name:'Hospitality',icon:'⌂',primary:'guests',related:'stays',entity:'guest',entityPlural:'guests',tables:['guests','rooms','stays','charges'],schema:['guests: id, name, country','rooms: id, room_type, nightly_rate','stays: id, guest_id, room_id, checked_in_at','charges: id, stay_id, amount, charged_at'],setup:`CREATE TABLE guests (id INTEGER PRIMARY KEY, name TEXT, country TEXT); CREATE TABLE rooms (id INTEGER PRIMARY KEY, room_type TEXT, nightly_rate NUMERIC); CREATE TABLE stays (id INTEGER PRIMARY KEY, guest_id INTEGER, room_id INTEGER, checked_in_at DATE); CREATE TABLE charges (id INTEGER PRIMARY KEY, stay_id INTEGER, amount NUMERIC, charged_at DATE); INSERT INTO guests VALUES (1,'Ana','Spain'),(2,'Kabir','India'),(3,'Lin','China'); INSERT INTO rooms VALUES (1,'Suite',300),(2,'Standard',120); INSERT INTO stays VALUES (1,1,1,'2025-01-05'),(2,1,2,'2025-02-05'),(3,2,2,'2025-02-11'); INSERT INTO charges VALUES (1,1,320,'2025-01-06'),(2,2,140,'2025-02-06'),(3,3,130,'2025-02-12');`}
];

const loadedDomainKeys = new Set();
function domainProblems(domain){return labTemplates.map(([number,difficulty,title,tag,prompt])=>{const test=window.domainTestDefinition(number,domain);return {id:`${domain.key.slice(0,2).toUpperCase()}${number}`,title:`${domain.name}: ${title}`,level:difficulty,tag,desc:`<p>${test.objective}</p><p>Use the <b>Schema</b> tab to inspect the connected tables before writing your PostgreSQL query.</p>`,example:`Domain: ${domain.name}\n\n${domain.schema.join('\n')}\n\nRelationships:\n${domain.tables.slice(0,-1).map((table,i)=>`${table} → ${domain.tables[i+1]}`).join('\n')}`,query:`-- ${title}\n-- Write your PostgreSQL query here\nSELECT * FROM ${domain.primary} LIMIT 10;`,setup:domain.setup,expectedQuery:test.expectedQuery,schema:domain.schema.map(line=>{const [name,columns]=line.split(': ');return [name,columns.replaceAll(', ',' · ')];}),hint:'Start with the smallest useful SELECT. Add joins and aggregations one step at a time.'};});}
function showLabs(){document.body.classList.remove('practice-mode');document.body.classList.add('domains-mode');document.querySelector('#sidebar').classList.remove('open');document.querySelector('.content-grid').hidden=true;document.querySelector('#domainView').hidden=false;document.querySelector('#crumbTitle').textContent='Choose a domain';document.querySelector('#practiceLink').classList.remove('active');document.querySelector('#domainsLink').classList.add('active');}
function showPractice(context='independent'){document.body.classList.remove('domains-mode');document.body.classList.add('practice-mode');document.querySelector('.content-grid').hidden=false;document.querySelector('#domainView').hidden=true;document.querySelector('#practiceLink').classList.add('active');document.querySelector('#domainsLink').classList.remove('active');if(context==='independent'&&typeof activeDomainPrefix!=='undefined'){activeDomainPrefix=null;renderList();}}
function openDomain(key){const domain=domains.find(item=>item.key===key);if(!loadedDomainKeys.has(key)){problems.push(...domainProblems(domain));loadedDomainKeys.add(key);renderList();}const labProblems=problems.filter(problem=>problem.id.startsWith(key.slice(0,2).toUpperCase()));const detail=document.querySelector('#domainDetail');detail.hidden=false;detail.innerHTML=`<div class="domain-detail-head"><div><div class="eyebrow">${domain.name.toUpperCase()} DATASET</div><h2>${domain.name} challenge path</h2></div><p>20 challenges · Easy → Hard<br>Click any challenge to open its PostgreSQL workspace.</p></div><div class="domain-schema">${domain.tables.map((table,index)=>`<span>${table}</span>${index<domain.tables.length-1?'<b>→</b>':''}`).join('')}</div><div class="challenge-list">${labProblems.map(problem=>`<button class="challenge-row" data-problem="${problem.id}"><span class="challenge-code">${problem.id.slice(-2)}</span><span class="challenge-name">${problem.title.replace(`${domain.name}: `,'')}</span><span class="challenge-level ${problem.level.toLowerCase()}">${problem.level}</span></button>`).join('')}</div>`;detail.scrollIntoView({behavior:'smooth',block:'start'});document.querySelectorAll('.challenge-row').forEach(row=>row.onclick=()=>{showPractice();loadProblem(problems.findIndex(problem=>problem.id===row.dataset.problem));document.querySelector('#sidebar').classList.remove('open');});}
document.querySelector('#domainGrid').innerHTML=domains.map(domain=>`<button class="domain-card" data-domain="${domain.key}"><div class="domain-card-top"><span class="domain-icon">${domain.icon}</span><span class="domain-count">20 CHALLENGES</span></div><h2>${domain.name}</h2><p>Connected, interview-style data with realistic relationships and progressively harder analysis.</p><div class="relationship-map">${domain.tables.map((table,index)=>`<span>${table}</span>${index<domain.tables.length-1?'<i>→</i>':''}`).join('')}</div><span class="domain-open">Open lab →</span></button>`).join('');
document.querySelectorAll('.domain-card').forEach(card=>card.onclick=()=>openDomain(card.dataset.domain));
document.body.classList.add('practice-mode');document.querySelector('#domainsLink').onclick=event=>{event.preventDefault();showLabs();};document.querySelector('#practiceLink').onclick=event=>{event.preventDefault();showPractice();};
